FROM mariadb:latest

# ENV MYSQL_ROOT_PASSWORD=password
# COPY employees.sql /docker-entrypoint-initdb.d/
EXPOSE 3306
# RUN mkdir /appdata
# ADD  ./data.sql /appdata/data.sql
# RUN mysql source /docker-entrypoint-initdb.d/init.sql
WORKDIR /docker-entrypoint-initdb.d/